### ISSUE TITLE
Sometimes using your   <com.astuetz.PagerSlidingTabStrip crashes

### ISSUE THREAD

**Issue by hsharma0052** [jpardogo/PagerSlidingTabStrip#127]
version of your library i am using is compile 'com.jpardogo.materialtabstrip:library:1.1.0'  ..stack trace is 

java.lang.IllegalStateException: Observer com.astuetz.f@4190d0f8 was not registered.
       at android.database.Observable.unregisterObserver(Observable.java:69)
       at android.support.v4.view.be.unregisterDataSetObserver(PagerAdapter.java:294)
       at com.astuetz.PagerSlidingTabStrip.onDetachedFromWindow(PagerSlidingTabStrip.java:548)
       at android.view.View.dispatchDetachedFromWindow(View.java:12620)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2591)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2589)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2834)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5271)
       at android.view.ViewRootImpl.die(ViewRootImpl.java:5248)
       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:346)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:301)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3522)
       at android.app.ActivityThread.access$1400(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
 
Any help will be appreciated..Its urgent

**Comment by jpardogo** [comment]
That´s probably an error in your code and the way you are setting up the adapter. I f you send you implementation. I may be able to help.

**Comment by jpardogo** [comment]
23 without and answer and nobody else commented so I close the issue
