### ISSUE TITLE
BUG, switch from this(as a fragment) to a fragment, crashed!

### ISSUE THREAD

**Issue by MewX** [jpardogo/PagerSlidingTabStrip#71]
This happens when I set no adapter to mRecyclerView. I get this but running well:

```
E/RecyclerView﹕ No adapter attached; skipping layout
```

Here is the exception when detaching:

```
java.lang.IllegalStateException: Observer com.astuetz.PagerSlidingTabStrip$PagerAdapterObserver@419b0668 was not registered.
            at android.database.Observable.unregisterObserver(Observable.java:64)
            at android.support.v4.view.PagerAdapter.unregisterDataSetObserver(PagerAdapter.java:294)
            at com.astuetz.PagerSlidingTabStrip.onDetachedFromWindow(PagerSlidingTabStrip.java:552)
            at android.view.View.dispatchDetachedFromWindow(View.java:9848)
            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2342)
            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2340)
            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2340)
            at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3671)
            at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3651)
            at android.view.ViewGroup.removeView(ViewGroup.java:3599)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
            at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1223)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:696)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4503)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by MewX** [comment]
For example, the Observer source code is:

```
    /**
     * Removes a previously registered observer. The observer must not be null and it
     * must already have been registered.
     * @param observer the observer to unregister
     * @throws IllegalArgumentException the observer is null
     * @throws IllegalStateException the observer is not yet registered
     */
    public void unregisterObserver(T observer) {
        if (observer == null) {
            throw new IllegalArgumentException("The observer is null.");
        }
        synchronized(mObservers) {
            int index = mObservers.indexOf(observer);
            if (index == -1) {
                throw new IllegalStateException("Observer " + observer + " was not registered.");
            }
            mObservers.remove(index);
        }
    }
```


So, just edit like this can escape this:

```
    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        if (pager != null) {
            if (adapterObserver.isAttached()) {
                try {
                    pager.getAdapter().unregisterDataSetObserver(adapterObserver);
                }
                catch (IllegalStateException e) {
                    e.printStackTrace();
                }
                adapterObserver.setAttached(false);
            }
        }
    }
```

**Comment by jpardogo** [comment]
Why you don't set an adapter to your RecyclerView?

**Comment by MewX** [comment]
Oh, I found that was my fault. Thanks anyway.

I was wondering that I didn't want set an adapter at first, because I was not sure which adapter type to choose. I might get different types of data from server, so I had to decide which adapter to use after I fetched the data. Is there a good solution for this situation?

Now, I set a simple adapter to the RecyclerView in onCreate().
